---
id: "aop:config:validate"
short_description: "Validate AOP configuration file."
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/aop-sdk app:configuration:validate %configuration-file%"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%configuration-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "configuration-file"
      description: "Path to configuration file"
      type: string
