---
id: "aop:translation:create"
short_description: "Create AOP translation file."
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/aop-sdk app:translation:create %translation-file%"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%translation-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "translation-file"
      description: "Path to save translation file to"
      type: string
