services:
  question_helper:
    class: Symfony\Component\Console\Helper\QuestionHelper
  init_sdk_command:
    autowire: false
    class: SprykerSdk\Sdk\Presentation\Console\Commands\InitSdkCommand
    tags: ['console.command']
    arguments:
      - '@question_helper'
      - '@setting_repository'
      - '@doctrine.database_create_command'
      - '@doctrine_migrations.migrate_command'
      - '@yaml_parser'
      - '%kernel.project_dir%/src/SprykerSdk/Sdk/Extension/Settings/settings.yaml'
  init_project_command:
    autowire: false
    class: SprykerSdk\Sdk\Presentation\Console\Commands\InitProjectCommand
    tags: ['console.command']
    arguments:
      - '@question_helper'
      - '@project_setting_manager'
      - '@setting_repository'
      - '%project_settings_file%'
  setting_set_command:
    class: SprykerSdk\Sdk\Presentation\Console\Commands\SettingSetCommand
    tags: ['console.command']
    arguments:
      - '@project_setting_repository'
      - '@project_setting_manager'