---
id: "acp:manifest:validate"
short_description: "Validate ACP manifest file."
help: ~
stage: build
version: 0.2.0
command: "php %sdk_dir%/vendor/bin/acp app:manifest:validate %manifest-path%"
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TASK_TYPE_LOCAL_CLI
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%manifest-path%"
    value_resolver: STATIC
    optional: true
    configuration:
      alias: "manifest-path"
      option: "manifest-path"
      description: "Path to manifest file"
      type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_STRING
