---
id: 'validation:architecture'
short_description: 'Check the architectural correctness of your code'
help: ~
stage: debug
command: '%sdk_dir%/vendor/bin/phpmd ./src text %sdk_dir%/vendor/spryker/architecture-sniffer/src/ruleset.xml %strict% --minimumpriority %priority%'
type: local_cli
placeholders:
  - name: '%sdk_dir%'
    value_resolver: SDK_DIR
    optional: true
  - name: '%strict%'
    value_resolver: FLAG
    optional: false
    configuration:
      name: 'strict'
      description: 'Report silent violations'
      defaultValue: false
      settingPaths: []
      type: bool
  - name: '%priority%'
    value_resolver: STATIC
    optional: false
    configuration:
      name: 'priority'
      description: 'Minimal priority of rules to fail the validation'
      minValue: 1
      maxValue: 10
      defaultValue: 2
      settingPaths: []
      type: int
