---
id: 'hello:world'
short_description: 'Sends greetings'
help: 'Will greet the one using it'
stage: build
command: '/bin/echo "hello %world% %somebody%"'
type: local_cli
placeholders:
  - name: '%world%'
    value_resolver: \SprykerSdk\Sdk\Core\Appplication\ValueResolver\StaticValueResolver
    optional: false
    configuration:
      name: 'world'
      description: 'what is the world?'
      value: 'World'
  - name: '%somebody%'
    value_resolver: STATIC
    optional: false
    configuration:
      name: 'somebody'
      description: 'Who is somebody'
      value: 'Somebody'
