parameters:
  project_settings_file: .ssdk
services:
  value_receiver:
    abstract: true
    synthetic: true
  abstract_value_resolver:
    abstract: true
    synthetic: true
    arguments:
      - '@value_receiver'
  task_repository:
    synthetic: true
  event_logger:
    synthetic: true
  setting_repository:
    abstract: true
    synthetic: true
  value_resolver_registry:
    abstract: true
    synthetic: true
  placeholder_resolver:
    class: SprykerSdk\Sdk\Core\Appplication\Service\PlaceholderResolver
    arguments:
      - '@setting_repository'
      - '@value_resolver_registry'
  task_executor:
    class: SprykerSdk\Sdk\Core\Appplication\Service\TaskExecutor
    arguments:
      - !tagged_iterator command.runner
      - '@placeholder_resolver'
      - '@task_repository'
      - '@event_logger'
  project_setting_repository:
    abstract: true
    synthetic: true
  project_setting_manager:
    class: SprykerSdk\Sdk\Core\Appplication\Service\ProjectSettingManager
    arguments:
      - '@project_setting_repository'
      - '@setting_repository'