settings:
  - path: task_dirs
    initialization_description: Where can tasks be loaded from?
    strategy: merge
    init: true
    type: array
    is_project: false
    values:
      - src/SprykerSdk/Sdk/Tasks
  - path: setting_dirs
    initialization_description: Where can settings be loaded from?
    strategy: merge
    init: true
    type: array
    is_project: false
    values:
      - src/SprykerSdk/Sdk/Settings
  - path: value_resolver_dirs
    initialization_description: Where can value resolvers be loaded from?
    strategy: merge
    init: true
    type: array
    is_project: false
    values:
      - src/SprykerSdk/Sdk/ValueResolvers
  - path: project_dir
    initialization_description: Where is the project directory?
    strategy: overwrite
    init: true
    type: path
    is_project: true
    values: './'
  - path: report_usage_statistics
    initialization_description: Do you agree to send anonymous usage reports to help improving the SDK?
    strategy: overwrite
    init: true
    is_project: true
    type: bool
    values: false