parameters:
  project_settings_file: '.ssdk'
services:
    path_resolver:
    class: SprykerSdk\Sdk\Core\Appplication\Service\PathResolver
    arguments:
      - '%kernel.project_dir%'
  value_receiver:
    abstract: true
    synthetic: true
  abstract_value_resolver:
    abstract: true
    synthetic: true
    arguments:
      - '@value_receiver'
  task_repository:
    synthetic: true
  event_logger:
    abstract: true
    synthetic: true
  progress_bar:
    abstract: true
    synthetic: true
  setting_repository:
    abstract: true
    synthetic: true
  value_resolver_registry:
    abstract: true
    synthetic: true
  placeholder_resolver:
    public: true
    class: SprykerSdk\Sdk\Core\Appplication\Service\PlaceholderResolver
    arguments:
      - '@project_setting_repository'
      - '@value_resolver_registry'
  violation_convertor_resolver:
    class: SprykerSdk\Sdk\Core\Appplication\Service\Violation\ViolationConvertorResolver
    arguments:
        - '@converter_repository'
  violation_report_merger:
    class: SprykerSdk\Sdk\Core\Appplication\Service\Violation\ViolationReportMerger
  violation_report_generator:
    class: SprykerSdk\Sdk\Core\Appplication\Service\Violation\ViolationReportGenerator
    arguments:
      - '@violation_report_merger'
      - '@violation_report_repository'
      - '@violation_convertor_resolver'
  task_executor:
    public: true
    class: SprykerSdk\Sdk\Core\Appplication\Service\TaskExecutor
    arguments:
      - !tagged_iterator command.runner
      - '@placeholder_resolver'
      - '@task_repository'
      - '@event_logger'
      - '@progress_bar'
      - '@violation_report_generator'
  project_setting_repository:
    abstract: true
    synthetic: true
  project_setting_manager:
    class: SprykerSdk\Sdk\Core\Appplication\Service\SettingManager
    arguments:
      - '@project_setting_repository'
      - '@setting_repository'
